/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2022-02-20

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/
/* Includes */
#include "stm32f4xx.h"
#include "stm32f4xx_rcc.h"
#include "stm32f4xx_gpio.h"
#include "stm32f4xx_tim.h"
#include "misc.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/

const uint32_t Period = 20 - 1;
const uint32_t prescaler = 1 - 1;
const uint32_t pulse = 15;

void GPIOD_Config(void);
void initPWM(void);

int main()
{
    initPWM();
    while(1)
    {

    }
}

void initPWM()
{
     TIM_TimeBaseInitTypeDef timer;
     TIM_OCInitTypeDef timerPWM;

     RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM4, ENABLE);
     RCC_APB1PeriphClockCmd(RCC_APB1Periph_TIM3, ENABLE);

     GPIOD_Config();

     //activate alter function PD13
     //NO ALTERNATE FUNCTION FOR PD13 WITH TIM3 (TIM4_CH2 ONLY)
     GPIO_PinAFConfig(GPIOD,GPIO_PinSource13,GPIO_AF_TIM3);
     //activate alter function PD14
     GPIO_PinAFConfig(GPIOD,GPIO_PinSource14,GPIO_AF_TIM4);

     //Timer settings
     TIM_TimeBaseStructInit(&timer);
     timer.TIM_ClockDivision = TIM_CKD_DIV1;
     timer.TIM_CounterMode = TIM_CounterMode_Up;

     timer.TIM_Prescaler = prescaler;
     timer.TIM_Period = Period;

     TIM_TimeBaseInit(TIM4, &timer);
     TIM_TimeBaseInit(TIM3, &timer);
     TIM_OCStructInit(&timerPWM);

     timerPWM.TIM_Pulse = pulse;
     timerPWM.TIM_OCMode = TIM_OCMode_PWM1;
     timerPWM.TIM_OutputState = TIM_OutputState_Enable;
     timerPWM.TIM_OCPolarity = TIM_OCPolarity_High;

     TIM_OC2Init(TIM3, &timerPWM);
     //TIM_OC4Init(TIM4, &timerPWM); ?? TIM4_CH3 for PD14
     TIM_OC3Init(TIM4, &timerPWM);

     //Synch settings
     TIM_SelectOutputTrigger(TIM4, TIM_TRGOSource_Enable);//Master config
     TIM_SelectMasterSlaveMode(TIM4, TIM_MasterSlaveMode_Enable);
     TIM_SelectInputTrigger(TIM3, TIM_TS_ITR3);//Slave config
     TIM_SelectSlaveMode(TIM3, TIM_SlaveMode_Gated);

     TIM_SetCounter(TIM3, 10);

     TIM_Cmd(TIM3, ENABLE);
     TIM_Cmd(TIM4, ENABLE);
}

void GPIOD_Config(void) {
	GPIO_InitTypeDef gpioConf;
	RCC_AHB1PeriphClockCmd(RCC_AHB1Periph_GPIOD, ENABLE);
	gpioConf.GPIO_Pin = GPIO_Pin_13 | GPIO_Pin_14;
	gpioConf.GPIO_Mode = GPIO_Mode_AF;
	gpioConf.GPIO_Speed = GPIO_Speed_2MHz;
	gpioConf.GPIO_OType = GPIO_OType_PP;

	GPIO_Init(GPIOD, &gpioConf);
}


